name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Django tests for search_localization
        run: python manage.py test search_localization.tests
      
      - name: Run Django tests for weather_data
        run: python manage.py test weather_data.tests
      
      - name: Run build
        run: npm run build